export default [
  "whole",
  "bottle",
  "kilogram",
  "pound",
  "ounces",
  "milliliter",
  "grams",
  "teaspoon",
  "tablespoon",
  "tin",
  "block",
  "clove",
  "cup",
].sort((itemOne, itemTwo) => itemOne.localeCompare(itemTwo));
