default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: carson_development
  username: db_user
  password: 'password'

test:
  <<: *default
  database: carson_test
  username: db_user
  password: 'password'

production:
  <<: *default
  database: carson_production
  username: production_user
  password: <%= ENV['CARSON_API_DATABASE_PASSWORD'] %>
